-- MySQL Script generated by MySQL Workbench
-- Τετ 26 Οκτ 2016 12:56:39 μμ EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Drop old bids4job_db
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `bids4job_db`;
-- -----------------------------------------------------
-- Schema bids4job_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bids4job_db` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema bids4job_db
-- -----------------------------------------------------
USE `bids4job_db` ;

-- -----------------------------------------------------
-- Table `simple_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simple_user` (
  `simple_user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `simple_username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(72) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `active_account` BOOLEAN NOT NULL,
  `simple_photo` VARCHAR(50),
  PRIMARY KEY (`simple_user_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task` (
  `task_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `deadline` TIMESTAMP(0) NOT NULL,
  `work_field` VARCHAR(45) NOT NULL,
  `simple_user_id` INT NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `active_task` BOOLEAN NOT NULL,
  PRIMARY KEY (`task_id`),
  INDEX `fk_task_1_idx` (`simple_user_id` ASC),
  CONSTRAINT `fk_simple_user_to_task_1`
    FOREIGN KEY (`simple_user_id`)
    REFERENCES `simple_user` (`simple_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pro_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_user` (
  `pro_user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `profession` VARCHAR(45) NOT NULL,
  `pro_username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(72) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `active_account` BOOLEAN NOT NULL,
  `pro_photo` VARCHAR(50),
  PRIMARY KEY (`pro_user_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `bid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bid` (
  `bid_id` INT NOT NULL AUTO_INCREMENT,
  `task_id` INT NOT NULL,
  `pro_user_id` INT NOT NULL,
  `amount` INT NOT NULL,
  `bid_time` TIMESTAMP(0) NOT NULL,
  PRIMARY KEY (`bid_id`),
  INDEX `fk_Bid_1_idx` (`pro_user_id` ASC),
  INDEX `fk_Bid_2_idx` (`task_id` ASC),
  CONSTRAINT `fk_pro_user_to_bid_1`
    FOREIGN KEY (`pro_user_id`)
    REFERENCES `pro_user` (`pro_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_to_bid_1`
    FOREIGN KEY (`task_id`)
    REFERENCES `task` (`task_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contract` (
  `contract_id` INT NOT NULL AUTO_INCREMENT,
  `bid_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  `contract_time` TIMESTAMP(0) NOT NULL,
  `rating` DOUBLE NULL,
  PRIMARY KEY (`contract_id`),
  INDEX `fk_contract_tasks1_idx` (`task_id` ASC),
  CONSTRAINT `fk_bid_to_contract_1`
    FOREIGN KEY (`bid_id`)
    REFERENCES `bid` (`bid_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_to_contract_1`
    FOREIGN KEY (`task_id`)
    REFERENCES `task` (`task_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;