INSERT INTO `bids4job_db`.`pro_user` (`pro_user_id`, `first_name`, `last_name`, `location`, `profession`) VALUES ('1', 'John', 'Kranas', 'Faliro', 'Developer');
INSERT INTO `bids4job_db`.`pro_user` (`pro_user_id`, `first_name`, `last_name`, `location`, `profession`) VALUES ('2', 'Petros', 'Petrou', 'Alimos', 'Barber');
INSERT INTO `bids4job_db`.`pro_user` (`pro_user_id`, `first_name`, `last_name`, `location`, `profession`) VALUES ('3', 'Dimitris', 'Kranas', 'Glyfada', 'Banker');
INSERT INTO `bids4job_db`.`pro_user` (`pro_user_id`, `first_name`, `last_name`, `location`, `profession`) VALUES ('4', 'Maria', 'Ioannou', 'Faliro', 'Dancer');
INSERT INTO `bids4job_db`.`pro_user` (`pro_user_id`, `first_name`, `last_name`, `location`, `profession`) VALUES ('5', 'Marialena', 'Rossetou', 'Chania', 'Designer');
INSERT INTO `bids4job_db`.`pro_user` (`pro_user_id`, `first_name`, `last_name`, `location`, `profession`) VALUES ('6', 'Apostolis', 'Chatzignatiou', 'Agios Dimitrios', 'Logistics');
INSERT INTO `bids4job_db`.`pro_user` (`pro_user_id`, `first_name`, `last_name`, `location`, `profession`) VALUES ('7', 'Kostas', 'Chatzinathanail', 'Argyroupoli', 'Personal Trainer');
INSERT INTO `bids4job_db`.`pro_user` (`pro_user_id`, `first_name`, `last_name`, `location`, `profession`) VALUES ('8', 'George', 'Chondrogiannis', 'Zografou', 'Barber');
INSERT INTO `bids4job_db`.`pro_user` (`pro_user_id`, `first_name`, `last_name`, `location`, `profession`) VALUES ('9', 'Chris', 'Stefanou', 'Kallithea', 'Developer');
INSERT INTO `bids4job_db`.`pro_user` (`pro_user_id`, `first_name`, `last_name`, `location`, `profession`) VALUES ('10', 'Pavlos', 'Kranas', 'Kentro', 'Developer');
INSERT INTO `bids4job_db`.`pro_user` (`pro_user_id`, `first_name`, `last_name`, `location`, `profession`) VALUES ('11', 'Athanasia', 'Gerontiou', 'Glyfada', 'Barber');
INSERT INTO `bids4job_db`.`pro_user` (`pro_user_id`, `first_name`, `last_name`, `location`, `profession`) VALUES ('12', 'Petros', 'Tsoulis', 'Alimos', 'Designer');
INSERT INTO `bids4job_db`.`pro_user` (`pro_user_id`, `first_name`, `last_name`, `location`, `profession`) VALUES ('13', 'Vasilis', 'Makakis', 'Kentro', 'Engineer');
INSERT INTO `bids4job_db`.`pro_user` (`pro_user_id`, `first_name`, `last_name`, `location`, `profession`) VALUES ('14', 'Achilleas', 'Tasoulis', 'Glyfada', 'Banker');
INSERT INTO `bids4job_db`.`pro_user` (`pro_user_id`, `first_name`, `last_name`, `location`, `profession`) VALUES ('15', 'Tasos', 'Petroulis', 'Zografou', 'Plumber');
INSERT INTO `bids4job_db`.`pro_user` (`pro_user_id`, `first_name`, `last_name`, `location`, `profession`) VALUES ('16', 'Makis', 'Spyridakis', 'Alimos', 'Designer');
INSERT INTO `bids4job_db`.`pro_user` (`pro_user_id`, `first_name`, `last_name`, `location`, `profession`) VALUES ('17', 'Sotiris', 'Petrou', 'Argyroupoli', 'Plumber');
INSERT INTO `bids4job_db`.`pro_user` (`pro_user_id`, `first_name`, `last_name`, `location`, `profession`) VALUES ('18', 'John', 'Tsaousis', 'Exarcheia', 'Developer');
INSERT INTO `bids4job_db`.`pro_user` (`pro_user_id`, `first_name`, `last_name`, `location`, `profession`) VALUES ('19', 'Dimitris', 'Theodoropoulos', 'Neo Iraklio', 'Developer');
INSERT INTO `bids4job_db`.`pro_user` (`pro_user_id`, `first_name`, `last_name`, `location`, `profession`) VALUES ('20', 'George', 'Bartzis', 'Chalandri', 'Developer');
INSERT INTO `bids4job_db`.`pro_user` (`pro_user_id`, `first_name`, `last_name`, `location`, `profession`) VALUES ('21', 'Nick', 'Vrimonis', 'Chalandri', 'Developer');
INSERT INTO `bids4job_db`.`pro_user` (`pro_user_id`, `first_name`, `last_name`, `location`, `profession`) VALUES ('22', 'Olga', 'Maki', 'Exarcheia', 'Personal Trainer');
INSERT INTO `bids4job_db`.`pro_user` (`pro_user_id`, `first_name`, `last_name`, `location`, `profession`) VALUES ('23', 'Fotis', 'Stefanou', 'Faliro', 'Plumber');
INSERT INTO `bids4job_db`.`pro_user` (`pro_user_id`, `first_name`, `last_name`, `location`, `profession`) VALUES ('24', 'Maria', 'Kostala', 'Chalandri', 'Designer');
