INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('1', '2016:1:09', 'Barber', '1');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('2', '2016:1:10', 'Barber', '4');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('3', '2016:1:12', 'Barber', '6');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('4', '2016:1:12', 'Barber', '8');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('5', '2016:1:12', 'Barber', '11');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('6', '2016:1:13', 'Developer', '1');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('7', '2016:1:13', 'Developer', '3');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('8', '2016:1:13', 'Developer', '7');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('9', '2016:1:13', 'Plumber', '1');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('10', '2016:1:13', 'Plumber', '1');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('11', '2016:1:13', 'Designer', '1');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('12', '2016:2:1', 'Plumber', '20');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('13', '2016:2:1', 'Designer', '20');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('14', '2016:2:15', 'Developer', '13');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('15', '2016:2:27', 'Barber', '19');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('16', '2016:3:7', 'Developer', '1');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('17', '2016:3:7', 'Developer', '1');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('18', '2016:3:30', 'Barber', '11');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('19', '2016:3:30', 'Developer', '6');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('20', '2016:4:9', 'Plumber', '6');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('21', '2016:4:9', 'Barber', '1');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('22', '2016:4:19', 'Plumber', '1');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('23', '2016:4:20', 'Developer', '17');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('24', '2016:4:22', 'Barber', '17');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('25', '2016:10:9', 'Developer', '17');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('26', '2016:10:9', 'Developer', '4');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('27', '2016:10:9', 'Barber', '5');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('28', '2016:10:9', 'Plumber', '5');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('29', '2016:10:10', 'Plumber', '7');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('30', '2016:10:10', 'Barber', '8');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('31', '2016:10:10', 'Barber', '9');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('32', '2016:10:10', 'Barber', '18');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('33', '2016:10:10', 'Plumber', '5');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('34', '2016:10:10', 'Developer', '5');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('35', '2016:10:10', 'Barber', '15');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('36', '2016:10:10', 'Plumber', '15');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('37', '2016:10:10', 'Barber', '15');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('38', '2016:10:10', 'Developer', '13');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('39', '2016:10:10', 'Barber', '11');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('40', '2016:11:1', 'Designer', '6');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('41', '2016:11:1', 'Developer', '8');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('42', '2016:11:1', 'Barber', '4');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('43', '2016:11:1', 'Barber', '3');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('44', '2016:11:1', 'Barber', '2');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('45', '2016:11:2', 'Developer', '2');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('46', '2016:11:2', 'Developer', '1');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('47', '2016:11:2', 'Developer', '7');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('48', '2016:11:2', 'Developer', '9');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('49', '2016:11:2', 'Developer', '2');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('50', '2016:11:3', 'Developer', '1');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('51', '2016:11:3', 'Developer', '1');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('52', '2016-12-03 00:00:00', 'Barber', '1');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('53', '2016-12-03 00:00:00', 'Barber', '3');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('54', '2016-12-03 00:00:00', 'Barber', '5');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('55', '2016-12-03 00:00:00', 'Engineer', '1');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('56', '2016-12-03 00:00:00', 'Plumber', '13');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('57', '2017-1-23 00:00:00', 'Barber', '1');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('58', '2017-1-23 00:00:00', 'Engineer', '13');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('59', '2017-1-23 00:00:00', 'Barber', '6');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('60', '2017-2-7 00:00:00', 'Driver', '5');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('61', '2017-2-23 00:00:00', 'Driver', '5');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('62', '2017-1-7 00:00:00', 'Engineer', '8');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('63', '2017-4-14 00:00:00', 'Barber', '11');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('64', '2017-4-24 00:00:00', 'Barber', '12');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('65', '2017-5-5 00:00:00', 'Barber', '15');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('66', '2017-5-24 00:00:00', 'Plumber', '11');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('67', '2017-1-4 00:00:00', 'Plumber', '20');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('68', '2017-1-11 00:00:00', 'Designer', '15');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('69', '2017-1-1 00:00:00', 'Developer', '1');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('70', '2017-1-11 00:00:00', 'Plumber', '12');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('71', '2017-2-2 00:00:00', 'Barber', '1');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('72', '2017-2-2 00:00:00', 'Barber', '2');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('73', '2017-1-4 00:00:00', 'Designer', '6');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('74', '2017-1-4 00:00:00', 'Driver', '5');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('75', '2017-1-4 00:00:00', 'Driver', '1');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('76', '2017-1-14 00:00:00', 'Developer', '15');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('77', '2017-1-23 00:00:00', 'Barber', '8');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('78', '2017-1-23 00:00:00', 'Plumber', '19');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('79', '2017-1-12 00:00:00', 'Designer', '1');
INSERT INTO `bids4job_db`.`task` (`task_id`, `deadline`, `work_field`, `simple_user_id`) VALUES ('80', '2017-2-3 00:00:00', 'Developer', '1');